version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskit_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - sqlite-data:/var/www/database
    networks:
      - taskit
    depends_on:
      - redis
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    image: nginx:alpine
    container_name: taskit_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - taskit
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: taskit_redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - taskit
    ports:
      - "6379:6379"

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskit_queue
    restart: unless-stopped
    command: php artisan queue:work
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - taskit
    depends_on:
      - app
      - db
      - redis

networks:
  taskit:
    driver: bridge

volumes:
  sqlite-data:
    driver: local
  redisdata:
    driver: local